### ISSUE TITLE
"UNK couldn't query the checksum table" - uknown explanation for pmp-check-pt-table-checksum

### ISSUE THREAD

**Issue by ShahriyarR** [percona/percona-monitoring-plugins#58]
For `pmp-check-pt-table-checksum` usage we have 3 different type of output:
```
# su -l nagios -c "env -i HOME=/usr/local/nagios /usr/local/nagios/libexec/pmp-check-pt-table-checksum"
UNK table 'percona.checksums' doesn't exist

# su -l nagios -c "env -i HOME=/usr/local/nagios /usr/local/nagios/libexec/pmp-check-pt-table-checksum"
OK pt-table-checksum found no out-of-sync tables
```

And:
```
# su -l nagios -c "env -i HOME=/usr/local/nagios /usr/local/nagios/libexec/pmp-check-pt-table-checksum"
UNK couldn't query the checksum table
```

So couldn't query? why?

How to reproduce:
```
mysql> use percona;
mysql> create table checksums(id int not null);
Query OK, 0 rows affected (0.01 sec)

# su -l nagios -c "env -i HOME=/usr/local/nagios /usr/local/nagios/libexec/pmp-check-pt-table-checksum"
```

It seems to be related to pt-table-checksum:

[PT-192](https://jira.percona.com/browse/PT-192)

Maybe improving UNK message or directly giving output from pt-table-checksum will be more informative.

**Comment by cezmunsta** [comment]
@ShahriyarR there is a risk of exposing information if you allow the message to report the error directly, so that would mean adding in all of the possible failure messages.

**Comment by ShahriyarR** [comment]
@cezmunsta Agree. Then closing.
