### ISSUE TITLE
Not able to view RDS instances under mumbai region

### ISSUE THREAD

**Issue by venki541** [percona/percona-monitoring-plugins#87]
Hi Team,
I am using this plugin to monitor my RDS instances under multiple accounts. For the RDS instances which are hosted in Singapore region, i can able to monitor successfully, but when i am trying to do the  same for Mumbai Region(ap-south-1), i am not able to view the region, is there anything i am lagging at configuration point of view.

BR
Venkatesh.P

**Comment by cezmunsta** [comment]
@venki541 the region is not present in the `boto` list of regions:
```
[RegionInfo:us-east-1, RegionInfo:cn-north-1, RegionInfo:ap-northeast-1, RegionInfo:eu-west-1, RegionInfo:ap-southeast-1, RegionInfo:ap-southeast-2, RegionInfo:us-west-2, RegionInfo:us-gov-west-1, RegionInfo:us-west-1, RegionInfo:eu-central-1, RegionInfo:sa-east-1]
```

**Comment by venki541** [comment]
Thanks for the update @cezmunsta 
Its the problem with permission on RDS for the policy defined, Now i am able to monitor the ap-south-1 region as well.
