### ISSUE TITLE
PMP and Vault

### ISSUE THREAD

**Issue by TimInNanoose** [percona/percona-monitoring-plugins#99]
Hi Team,

C **REDACTED** Thompson of **REDACTED** has found a bug in Percona Plugin with regards to Vault:

Also, Percona may want to include in their documentation for Vault that your plugin doesn't work with KV v2. It doesn't error out and when I encrypt tables it works perfectly fine, but doesn't create InnoDB tablespace encryption key in Vault.

Vault: https://www.vaultproject.io/

Tim

**Comment by rnovikovP** [comment]
this need to go to the Product manager
